# Generated by Django 6.1 on 2026-09-09 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text='icon (font version) from devicon.dev', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers display first')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='experience',
            name='thumbnail',
        ),
    ]
