# Generated by Django 6.1 on 2026-09-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills_remove_experience_thumbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
