# Generated by Django 5.2.17 on 2026-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_path',
            field=models.CharField(blank=True, help_text='icon (svg link) from devicon.dev', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
