# Generated by Django 5.2.17 on 2026-09-24 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_experience_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='endorsed_by',
            field=models.ManyToManyField(blank=True, related_name='endorsed_skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
